[package]
name = "tama"
version = "0.1.0"
authors = ["jrx <jerome@rouaix.eu>"]
edition = "2021"
resolver = "2"
rust-version = "1.71"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[dependencies]

defmt = "0.3"
defmt-rtt = "0.4"

# Embassy
embassy-executor = { version = "0.5", default-features = false }
embassy-sync = { version = "0.5", default-features = false, features = [
    "defmt",
] }
embassy-time = { version = "0.3", default-features = false, features = [
    "defmt",
    "defmt-timestamp-uptime",
    "tick-hz-8",              # very low
] }
embassy-net = { version = "0.4", default-features = false }

# Hardware Abstraction Layer
embedded-hal = { version = "1", default-features = false }
embedded-hal-async = { version = "1", default-features = false }
embedded-hal-bus = { version = "0.1", default-features = false }
embedded-io-async = { version = "0.6", default-features = false }

# ESP specifics
esp-hal = { version = "0.16", default-features = false }
esp-backtrace = { version = "0.11", default-features = false }
esp-println = { version = "0.9", default-features = false }
esp-wifi = { version = "0.4", default-features = false }

# Logging
log = { version = "0.4", default-features = false }

esp-idf-hal = "0.43"
mipidsi = "0.7"
display-interface-spi = "0.5"

embedded-graphics = "0.8"

# embassy-executor = { version = "0.5", features = [
#     "arch-cortex-m",
#     "executor-thread",
#     "defmt",
#     "integrated-timers",
# ] }
# embassy-time = { version = "0.3", features = [
#     "defmt",
#     "defmt-timestamp-uptime",
#     "tick-hz-32_768",
# ] }

panic-probe = { version = "0.3", features = ["print-defmt"] }
futures = { version = "0.3.17", default-features = false, features = [
    "async-await",
] }
heapless = { version = "0.8", default-features = false }

[build-dependencies]
embuild = "0.31.3"
